# Generated by Django 6.0.1 on 2026-01-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comment_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
